<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24" started-at="2015-07-14T05:21:05Z" finished-at="2015-07-14T05:21:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24" started-at="2015-07-14T05:21:05Z" finished-at="2015-07-14T05:21:05Z">
      <class name="first.my.SampleClass">
        <test-method status="PASS" signature="TestFirst()[pri:0, instance:first.my.SampleClass@5c0369c4]" name="TestFirst" duration-ms="10" started-at="2015-07-13T22:21:05Z" finished-at="2015-07-13T22:21:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestFirst -->
        <test-method status="FAIL" signature="TestSecond()[pri:0, instance:first.my.SampleClass@5c0369c4]" name="TestSecond" duration-ms="1" started-at="2015-07-13T22:21:05Z" finished-at="2015-07-13T22:21:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [first] but found [first1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [first] but found [first1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at first.my.SampleClass.TestSecond(SampleClass.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSecond -->
        <test-method status="PASS" signature="TestThird()[pri:0, instance:first.my.SampleClass@5c0369c4]" name="TestThird" duration-ms="1" started-at="2015-07-13T22:21:05Z" finished-at="2015-07-13T22:21:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestThird -->
      </class> <!-- first.my.SampleClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
